services:
  viacep-mock:
    image: wiremock/wiremock:3.9.1
    volumes:
      - ./imobifix-api/test/viacep-mock/mappings:/home/wiremock/mappings:ro
    ports:
      - "8090:8080" 

  imobifix-api:
    depends_on:
      - viacep-mock
    environment:
      VIA_CEP_BASE_URL: "http://viacep-mock:8080"